name: Streamlit deploy link
on:
  pull_request:    # A new PR is opened
    types: opened
    
# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
# To trigger the bot to comment with a Streamlit Cloud deploy link
jobs:
 comment:
   runs-on: ubuntu-latest
   steps:
     - name: Check branch  # scans for new PRs on 'develop' branch
       if: startsWith(github.event.pull_request.head.ref, 'develop')
       run: echo "Pull request is from the correct branch"
 
     - name: Post comment
       uses: thollander/actions-comment-pull-request@v2
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         message: |     # repo & branch paths are input query params for deploy dialog
           Thanks for the pull request! 
           You can now deploy this app using Streamlit here 👉 [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://share.streamlit.io/deploy?repository=${{ github.repository }}&branch=${{ github.branch }}&mainModule=streamlit_app.py)
           
