name: Streamlit deploy link
on:
  pull_request:
    types: opened
    
# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
 comment:
   runs-on: ubuntu-latest
   steps:
     - name: Check branch  # scans for new PRs
       if: startsWith(github.event.pull_request.head.ref, 'develop')
       run: echo "Pull request is from the correct branch"
 
     - name: Post comment
       uses: thollander/actions-comment-pull-request@v2
       with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         message: |
           Thanks for the pull request! You can deploy this app using Streamlit with the following link:
           [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://share.streamlit.io/deploy?repository=${{ github.repository }}&branch=${{ github.ref }}&mainModule=streamlit_app.py)
           
